import { useEffect, useState } from 'react';
import { createKnowledgeSource, loadKnowledgeSources, syncKnowledgeSource, type KnowledgeSource, type KnowledgeSourceScope } from '@/lib/crm/catalogKnowledgeRepository';

const suggestedSources: Array<{ name: string; url: string; scope: KnowledgeSourceScope; icon: string; description: string }> = [
  { name: 'Produtos e acessórios', url: 'https://wayflex.ind.br/acessorios', scope: 'products', icon: 'ri-shapes-line', description: 'Importa cards de acessórios, imagem e texto publicados na página oficial.' },
  { name: 'Segmentos e aplicações', url: 'https://wayflex.ind.br/servicos', scope: 'services', icon: 'ri-tools-line', description: 'Mantém os segmentos publicados separados dos produtos, sem inventar serviços ausentes.' },
  { name: 'Catálogos visuais', url: 'https://wayflex.ind.br/catalogos', scope: 'catalogs', icon: 'ri-book-open-line', description: 'Importa capa, categoria e descrição; PDF só aparece quando a fonte o publica.' },
];

function statusCopy(source: KnowledgeSource | undefined): { label: string; className: string } {
  if (!source) return { label: 'Não sincronizada', className: 'bg-background-100 text-foreground-600' };
  if (source.syncStatus === 'healthy') return { label: 'Sincronizada', className: 'bg-secondary-100 text-secondary-800' };
  if (source.syncStatus === 'error') return { label: 'Erro na última tentativa', className: 'bg-accent-100 text-accent-800' };
  if (source.syncStatus === 'syncing') return { label: 'Sincronizando', className: 'bg-primary-100 text-primary-800' };
  return { label: 'Aguardando sincronização', className: 'bg-background-100 text-foreground-600' };
}

export default function KnowledgeSourcesTab() {
  const [sources, setSources] = useState<KnowledgeSource[]>([]);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [manualOpen, setManualOpen] = useState(false);
  const [manual, setManual] = useState({ name: '', url: '', scope: 'mixed' as KnowledgeSourceScope });

  const refresh = async () => { setLoading(true); try { setSources(await loadKnowledgeSources()); setError(''); } catch { setError('Não foi possível carregar as fontes de conhecimento.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const sourceFor = (url: string) => sources.find((source) => source.sourceUrl.replace(/\/$/, '') === url.replace(/\/$/, ''));
  const sync = async (url: string) => { setSyncing(url); setError(''); try { const result = await syncKnowledgeSource(url); await refresh(); setNotice(result.message); } catch (cause) { setError(cause instanceof Error ? `A fonte não foi sincronizada: ${cause.message}.` : 'A fonte não foi sincronizada.'); } finally { setSyncing(null); } };
  const saveManual = async () => { try { await createKnowledgeSource({ name: manual.name, sourceUrl: manual.url, contentScope: manual.scope }); setManualOpen(false); setManual({ name: '', url: '', scope: 'mixed' }); await refresh(); setNotice('Fonte cadastrada. Adicione itens manualmente ou conecte um adaptador específico antes de sincronizar.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível cadastrar a fonte.'); } };

  return <div className="space-y-4">
    {notice && <div className="rounded-lg border border-secondary-200 bg-secondary-50 px-4 py-3 text-sm text-secondary-900"><i className="ri-checkbox-circle-line mr-2" />{notice}</div>}
    {error && <div className="rounded-lg border border-accent-200 bg-accent-50 px-4 py-3 text-sm text-accent-800"><i className="ri-error-warning-line mr-2" />{error}</div>}
    <section className="rounded-xl border border-background-200/70 bg-foreground-950 p-5 text-background-50"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-primary-200">Rastreabilidade</p><h2 className="mt-1 font-heading text-xl font-bold">Fontes de conhecimento</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-background-200">A sincronização registra URL, data, resultado e o conteúdo realmente publicado. Imagens permanecem referenciadas à origem oficial; nenhum preço, PDF ou especificação é criado quando a fonte não o mostra.</p></div><button type="button" onClick={() => setManualOpen(true)} className="inline-flex w-fit items-center gap-2 rounded-lg border border-background-50/25 px-3.5 py-2 text-xs font-semibold hover:bg-background-50/10"><i className="ri-add-line" />Cadastrar fonte</button></div></section>
    <div className="grid gap-3 xl:grid-cols-3">{suggestedSources.map((suggestion) => { const source = sourceFor(suggestion.url); const status = statusCopy(source); const isSyncing = syncing === suggestion.url; return <section key={suggestion.url} className="rounded-xl border border-background-200/70 bg-background-50 p-4"><div className="flex items-start justify-between gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-100 text-primary-700"><i className={suggestion.icon} /></span><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status.className}`}>{isSyncing ? 'Sincronizando' : status.label}</span></div><h3 className="mt-4 text-sm font-bold text-foreground-900">{suggestion.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-foreground-500">{suggestion.description}</p><a href={suggestion.url} target="_blank" rel="noreferrer" className="mt-3 block truncate text-xs text-primary-700 underline" title={suggestion.url}>{suggestion.url}</a>{source?.lastError && <p className="mt-2 text-xs text-accent-700">Último erro: {source.lastError}</p>}<button type="button" onClick={() => void sync(suggestion.url)} disabled={Boolean(syncing)} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary-500 px-3 py-2 text-xs font-semibold text-background-50 transition hover:bg-primary-600 disabled:cursor-wait disabled:bg-primary-300"><i className={isSyncing ? 'ri-loader-4-line animate-spin' : 'ri-refresh-line'} />{source ? 'Atualizar fonte' : 'Conectar e sincronizar'}</button></section>; })}</div>
    <section className="overflow-hidden rounded-xl border border-background-200/70 bg-background-50"><div className="flex items-center justify-between border-b border-background-200/70 px-5 py-3"><h3 className="text-sm font-bold text-foreground-900">Fontes cadastradas</h3><span className="text-xs text-foreground-500">{loading ? 'Carregando…' : `${sources.length} fonte(s)`}</span></div>{!loading && sources.length === 0 ? <div className="px-5 py-10 text-center text-sm text-foreground-500"><i className="ri-radar-line mb-2 block text-3xl" />Conecte uma fonte oficial para começar.</div> : <div className="divide-y divide-background-100">{sources.map((source) => { const status = statusCopy(source); return <div key={source.id} className="flex flex-col gap-2 px-5 py-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><p className="truncate text-sm font-semibold text-foreground-900">{source.name}</p><p className="mt-0.5 truncate text-xs text-foreground-500">{source.sourceUrl}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status.className}`}>{status.label}</span><span className="text-xs text-foreground-500">{source.lastSyncedAt ? new Date(source.lastSyncedAt).toLocaleString('pt-BR') : 'sem execução'}</span></div></div>; })}</div>}</section>
    {manualOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground-950/50 p-4" onClick={() => setManualOpen(false)}><div className="w-full max-w-md rounded-xl bg-background-50" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-background-200/70 px-5 py-4"><h3 className="font-heading font-bold text-foreground-950">Cadastrar fonte futura</h3><button type="button" onClick={() => setManualOpen(false)} className="rounded-lg p-1 hover:bg-background-100"><i className="ri-close-line text-lg" /></button></div><div className="space-y-4 p-5"><p className="text-xs leading-5 text-foreground-500">Esta ação só registra a origem. Ela não inicia uma coleta em sites que ainda não possuem adaptador homologado.</p><label className="block text-sm font-medium">Nome<input value={manual.name} onChange={(event) => setManual({ ...manual, name: event.target.value })} className="mt-1.5 w-full rounded-lg border border-background-300 px-3 py-2.5 text-sm" /></label><label className="block text-sm font-medium">URL<input type="url" value={manual.url} onChange={(event) => setManual({ ...manual, url: event.target.value })} placeholder="https://" className="mt-1.5 w-full rounded-lg border border-background-300 px-3 py-2.5 text-sm" /></label><label className="block text-sm font-medium">Tipo de conteúdo<select value={manual.scope} onChange={(event) => setManual({ ...manual, scope: event.target.value as KnowledgeSourceScope })} className="mt-1.5 w-full rounded-lg border border-background-300 px-3 py-2.5 text-sm"><option value="mixed">Misto</option><option value="products">Produtos</option><option value="services">Serviços</option><option value="catalogs">Catálogos</option><option value="documents">Documentos</option></select></label></div><div className="flex justify-end gap-2 border-t border-background-200/70 px-5 py-4"><button type="button" onClick={() => setManualOpen(false)} className="rounded-lg border border-background-300 px-3 py-2 text-sm font-semibold">Cancelar</button><button type="button" onClick={() => void saveManual()} className="rounded-lg bg-primary-500 px-4 py-2 text-sm font-semibold text-background-50 hover:bg-primary-600">Cadastrar</button></div></div></div>}
  </div>;
}
