/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as PortalVendedorRouteImport } from './routes/portal-vendedor'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalVendedorRoute = PortalVendedorRouteImport.update({
  id: '/portal-vendedor',
  path: '/portal-vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/leads': typeof LeadsRouteWithChildren
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/portal-vendedor': typeof PortalVendedorRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/leads': typeof LeadsRouteWithChildren
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/portal-vendedor': typeof PortalVendedorRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/leads': typeof LeadsRouteWithChildren
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/portal-vendedor': typeof PortalVendedorRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/prospeccao'
    | '/relatorios'
    | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/prospeccao'
    | '/relatorios'
    | '/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/prospeccao'
    | '/relatorios'
    | '/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmpresaRoute: typeof EmpresaRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  OrcamentosRoute: typeof OrcamentosRoute
  PedidosRoute: typeof PedidosRoute
  PortalVendedorRoute: typeof PortalVendedorRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-vendedor': {
      id: '/portal-vendedor'
      path: '/portal-vendedor'
      fullPath: '/portal-vendedor'
      preLoaderRoute: typeof PortalVendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmpresaRoute: EmpresaRoute,
  LeadsRoute: LeadsRouteWithChildren,
  OrcamentosRoute: OrcamentosRoute,
  PedidosRoute: PedidosRoute,
  PortalVendedorRoute: PortalVendedorRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
