/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiAnaRouteImport } from './routes/api/ana'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProspeccaoRouteImport } from './routes/_authenticated/prospeccao'
import { Route as AuthenticatedPortalVendedorRouteImport } from './routes/_authenticated/portal-vendedor'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const ApiAnaRoute = ApiAnaRouteImport.update({
  id: '/api/ana',
  path: '/api/ana',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProspeccaoRoute = AuthenticatedProspeccaoRouteImport.update({
  id: '/_authenticated/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalVendedorRoute =
  AuthenticatedPortalVendedorRouteImport.update({
    id: '/_authenticated/portal-vendedor',
    path: '/portal-vendedor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/_authenticated/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/_authenticated/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/_authenticated/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/_authenticated/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/_authenticated/atendimento',
    path: '/atendimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/ana': typeof ApiAnaRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesByTo {
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/ana': typeof ApiAnaRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/portal-vendedor': typeof AuthenticatedPortalVendedorRoute
  '/_authenticated/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/ana': typeof ApiAnaRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/atendimento'
    | '/configuracoes'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/prospeccao'
    | '/relatorios'
    | '/api/ana'
    | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atendimento'
    | '/configuracoes'
    | '/empresa'
    | '/leads'
    | '/orcamentos'
    | '/pedidos'
    | '/portal-vendedor'
    | '/prospeccao'
    | '/relatorios'
    | '/api/ana'
    | '/leads/$id'
  id:
    | '__root__'
    | '/_authenticated/atendimento'
    | '/_authenticated/configuracoes'
    | '/_authenticated/empresa'
    | '/_authenticated/leads'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pedidos'
    | '/_authenticated/portal-vendedor'
    | '/_authenticated/prospeccao'
    | '/_authenticated/relatorios'
    | '/api/ana'
    | '/_authenticated/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPortalVendedorRoute: typeof AuthenticatedPortalVendedorRoute
  AuthenticatedProspeccaoRoute: typeof AuthenticatedProspeccaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  ApiAnaRoute: typeof ApiAnaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/ana': {
      id: '/api/ana'
      path: '/api/ana'
      fullPath: '/api/ana'
      preLoaderRoute: typeof ApiAnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prospeccao': {
      id: '/_authenticated/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AuthenticatedProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal-vendedor': {
      id: '/_authenticated/portal-vendedor'
      path: '/portal-vendedor'
      fullPath: '/portal-vendedor'
      preLoaderRoute: typeof AuthenticatedPortalVendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPortalVendedorRoute: AuthenticatedPortalVendedorRoute,
  AuthenticatedProspeccaoRoute: AuthenticatedProspeccaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  ApiAnaRoute: ApiAnaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
