// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjbcshrzzwxijcslrlnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqYmNzaHJ6end4aWpjc2xybG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NDU5MTYsImV4cCI6MjA5OTUyMTkxNn0.iRW7KmiPr4oNp2eORFlfEhIdlGbpMlsoZ2mPuD5YaHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});