import { createAdminClient, requireOrganizationRole, requireUser } from '../_shared/auth.ts';
import { allowedCorsHeaders, hasAllowedOrigin, json, preflight, safeError } from '../_shared/http.ts';

const CATEGORIES=new Set(['institucional','materiais','solucoes_e_produtos','qualificacao','regras_comerciais','respostas_aprovadas','handoff_humano']);
const KINDS=new Set(['documento','imagem','apresentacao','planilha','video','link','texto']);
const ACTIONS=new Set(['register','save_text','publish','unpublish','delete','reindex_embeddings']);
const asText=(v:unknown,m=120000):string=>typeof v==='string'?v.trim().slice(0,m):'';
const asObject=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const asList=(v:unknown,m=20):string[]=>Array.isArray(v)?v.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(Boolean).slice(0,m):[];
const isUuid=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
type Admin=ReturnType<typeof createAdminClient>;

function validUrl(v:string):string|null{if(!v)return null;try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.toString():null}catch{return null}}
function chunksFrom(content:string):string[]{const clean=content.replace(/\r/g,'').trim();if(!clean)return[];const chunks:string[]=[];let current='';for(const p of clean.split(/\n{2,}/)){const next=p.trim();if(!next)continue;if(current&&current.length+next.length+2>1800){chunks.push(current);current=next}else current=current?`${current}\n\n${next}`:next}if(current)chunks.push(current);if(!chunks.length)chunks.push(clean.slice(0,1800));return chunks.slice(0,40)}
function metadataFor(input:Record<string,unknown>,previous:Record<string,unknown>={}){const category=asText(input.category,80),kind=asText(input.kind,32);return{...previous,ana_memory:true,category:CATEGORIES.has(category)?category:(previous.category||'institucional'),kind:KINDS.has(kind)?kind:(previous.kind||'documento'),tags:asList(input.tags),linked_product_id:isUuid(asText(input.linked_product_id,80))?asText(input.linked_product_id,80):null,source_label:asText(input.source_label,180)||null,processing_note:asText(input.processing_note,1200)||null,content_status:asText(input.content_status,32)||previous.content_status||'needs_review'}}
async function organizationFor(request:Request){const{user}=await requireUser(request);const admin=createAdminClient();const{data:profile,error}=await admin.from('profiles').select('active_organization_id,name').eq('id',user.id).maybeSingle();if(error||!profile?.active_organization_id)throw new Error('organization_context_required');const organizationId=profile.active_organization_id as string;await requireOrganizationRole(admin,user.id,organizationId,['owner','admin','manager']);return{admin,user,organizationId,actorName:profile.name||'Usuário'}}
async function openAiKey(admin:Admin,org:string):Promise<string|null>{const{data:i,error}=await admin.from('integrations').select('id,enabled,connected,paused').eq('organization_id',org).eq('key','ai').maybeSingle();if(error||!i?.enabled||!i.connected||i.paused)return null;const{data:s,error:se}=await admin.rpc('read_integration_secret',{p_integration:i.id});if(se||!s||typeof s!=='object')return null;return asText((s as Record<string,unknown>).openai_key,1000)||null}
async function embeddingsFor(admin:Admin,org:string,texts:string[]):Promise<number[][]|null>{if(!texts.length)return[];const key=await openAiKey(admin,org);if(!key)return null;let r:Response;try{r=await fetch('https://api.openai.com/v1/embeddings',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'text-embedding-3-small',dimensions:1536,input:texts}),signal:AbortSignal.timeout(30000)})}catch{throw new Error('embedding_network_error')}if(!r.ok)throw new Error(`embedding_provider_${r.status}`);const b=await r.json() as{data?:Array<{index?:number;embedding?:number[]}>};const rows=(b.data??[]).slice().sort((a,b)=>Number(a.index??0)-Number(b.index??0));if(rows.length!==texts.length||rows.some(x=>!Array.isArray(x.embedding)||x.embedding?.length!==1536))throw new Error('embedding_invalid_response');return rows.map(x=>x.embedding as number[])}
async function buildRows(admin:Admin,org:string,doc:string,chunks:string[],status:string,metadata:Record<string,unknown>){let embeddings:number[][]|null=null,error:string|null=null;try{embeddings=await embeddingsFor(admin,org,chunks)}catch(e){error=safeError(e)}const now=new Date().toISOString();return{rows:chunks.map((content,index)=>({organization_id:org,document_id:doc,chunk_index:index,content,tokens:Math.ceil(content.length/4),status,metadata:{...metadata,embedding_model:embeddings?'text-embedding-3-small':null,embedding_indexed_at:embeddings?now:null},embedding:embeddings?.[index]??null})),embeddingError:error}}
async function backfill(admin:Admin,org:string,doc?:string|null){let q=admin.from('knowledge_chunks').select('id,content,metadata').eq('organization_id',org).eq('status','active').is('embedding',null).order('created_at',{ascending:true}).limit(40);if(doc)q=q.eq('document_id',doc);const{data:chunks,error}=await q;if(error)throw error;if(!chunks?.length)return{processed:0,remaining:0,provider:'none'};const vectors=await embeddingsFor(admin,org,chunks.map(x=>x.content));if(!vectors)return{processed:0,remaining:chunks.length,provider:'not_configured'};let processed=0;const indexedAt=new Date().toISOString();for(let i=0;i<chunks.length;i++){const metadata={...asObject(chunks[i].metadata),embedding_model:'text-embedding-3-small',embedding_indexed_at:indexedAt};const{error:e}=await admin.from('knowledge_chunks').update({embedding:vectors[i],metadata}).eq('id',chunks[i].id).eq('organization_id',org).is('embedding',null);if(e)throw e;processed++}const{count}=await admin.from('knowledge_chunks').select('id',{count:'exact',head:true}).eq('organization_id',org).eq('status','active').is('embedding',null);return{processed,remaining:count??0,provider:'openai'}}

Deno.serve(async(request)=>{const pf=preflight(request);if(pf)return pf;if(!hasAllowedOrigin(request))return json({ok:false,erro:'origin_not_allowed'},403);const headers=allowedCorsHeaders(request);if(request.method!=='POST')return json({ok:false,erro:'method_not_allowed'},405,headers);try{const body=asObject(await request.json());const action=asText(body.action,32);if(!ACTIONS.has(action))throw new Error('unsupported_action');const{admin,user,organizationId,actorName}=await organizationFor(request);const documentId=asText(body.document_id,80);
if(action==='reindex_embeddings'){if(documentId&&!isUuid(documentId))throw new Error('document_id_invalid');const result=await backfill(admin,organizationId,documentId||null);await admin.from('audit_logs').insert({organization_id:organizationId,actor_id:user.id,actor_name:actorName,actor_type:'user',action:'ana.knowledge_embeddings_reindexed',detail:'Embeddings da Base da Ana reindexados.',entity_table:'knowledge_chunks',event_data:result});return json({ok:true,...result},200,headers)}
if(action==='register'){const name=asText(body.name,180),storagePath=asText(body.storage_path,500),sourceUrl=validUrl(asText(body.source_url,2000));if(!name)throw new Error('document_name_required');if(!storagePath&&!sourceUrl)throw new Error('document_source_required');if(storagePath&&!storagePath.startsWith(`${organizationId}/ana/`))throw new Error('invalid_storage_path');if(storagePath){const{error}=await admin.storage.from('ana-knowledge').createSignedUrl(storagePath,60);if(error)throw new Error('uploaded_file_not_found')}const content=asText(body.content),metadata=metadataFor(body);const{data:document,error}=await admin.from('documents').insert({organization_id:organizationId,name,content_text:content||null,storage_path:storagePath||null,type:asText(body.mime_type,160)||null,size:asText(body.size,32)||null,status:content?'draft':'processing',source_type:sourceUrl?'url':'upload',source_url:sourceUrl,category:'knowledge',visibility:'ai',uploaded_by:user.id,metadata}).select('id').single();if(error||!document)throw error??new Error('document_not_created');const chunks=chunksFrom(content);let embeddingError:string|null=null;if(chunks.length){const built=await buildRows(admin,organizationId,document.id,chunks,'draft',metadata);embeddingError=built.embeddingError;const{error:e}=await admin.from('knowledge_chunks').insert(built.rows);if(e)throw e}if(embeddingError)await admin.from('documents').update({index_error:embeddingError}).eq('id',document.id).eq('organization_id',organizationId);await admin.from('audit_logs').insert({organization_id:organizationId,actor_id:user.id,actor_name:actorName,actor_type:'user',action:'ana.knowledge_registered',detail:'Fonte adicionada à Base aprovada da Ana.',entity_table:'documents',entity_id:document.id,event_data:{kind:metadata.kind,category:metadata.category,has_content:Boolean(chunks.length),semantic_index:!embeddingError}});return json({ok:true,document_id:document.id,status:chunks.length?'draft':'processing',semantic_index:!embeddingError,embedding_error:embeddingError},201,headers)}
if(!isUuid(documentId))throw new Error('document_id_required');const{data:existing,error:existingError}=await admin.from('documents').select('id,storage_path,metadata,name').eq('id',documentId).eq('organization_id',organizationId).maybeSingle();if(existingError||!existing)throw existingError??new Error('document_not_found');
if(action==='save_text'){const content=asText(body.content);if(!content)throw new Error('content_required');const metadata=metadataFor(body,asObject(existing.metadata)),chunks=chunksFrom(content),built=await buildRows(admin,organizationId,documentId,chunks,'draft',metadata);const{error:u}=await admin.from('documents').update({content_text:content,status:'draft',metadata,index_error:built.embeddingError,indexed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',documentId).eq('organization_id',organizationId);if(u)throw u;const{error:d}=await admin.from('knowledge_chunks').delete().eq('document_id',documentId).eq('organization_id',organizationId);if(d)throw d;const{error:i}=await admin.from('knowledge_chunks').insert(built.rows);if(i)throw i;await admin.from('audit_logs').insert({organization_id:organizationId,actor_id:user.id,actor_name:actorName,actor_type:'user',action:'ana.knowledge_text_reviewed',detail:'Texto revisado da fonte da Ana.',entity_table:'documents',entity_id:documentId,event_data:{chunks:chunks.length,semantic_index:!built.embeddingError}});return json({ok:true,status:'draft',chunks:chunks.length,semantic_index:!built.embeddingError,embedding_error:built.embeddingError},200,headers)}
if(action==='publish'||action==='unpublish'){const publish=action==='publish';if(publish){const{count,error}=await admin.from('knowledge_chunks').select('id',{count:'exact',head:true}).eq('document_id',documentId).eq('organization_id',organizationId);if(error)throw error;if(!count)throw new Error('reviewed_text_required')}const nextMetadata={...asObject(existing.metadata),ana_memory:true,approval_status:publish?'approved':'draft',...(publish?{ana_approved_at:new Date().toISOString(),ana_approved_by:user.id}:{})};const nextStatus=publish?'active':'draft';const{error:de}=await admin.from('documents').update({status:nextStatus,metadata:nextMetadata,updated_at:new Date().toISOString(),indexed_at:publish?new Date().toISOString():null}).eq('id',documentId).eq('organization_id',organizationId);if(de)throw de;const{data:rows,error:re}=await admin.from('knowledge_chunks').select('id,metadata').eq('document_id',documentId).eq('organization_id',organizationId);if(re)throw re;for(const row of rows??[]){const{error:e}=await admin.from('knowledge_chunks').update({status:nextStatus,metadata:{...asObject(row.metadata),...nextMetadata}}).eq('id',row.id).eq('organization_id',organizationId);if(e)throw e}let semantic:Record<string,unknown>={processed:0,remaining:0,provider:'none'};if(publish){try{semantic=await backfill(admin,organizationId,documentId)}catch(e){const code=safeError(e);semantic={processed:0,remaining:null,provider:'error',error:code};await admin.from('documents').update({index_error:code}).eq('id',documentId).eq('organization_id',organizationId)}}await admin.from('audit_logs').insert({organization_id:organizationId,actor_id:user.id,actor_name:actorName,actor_type:'user',action:publish?'ana.knowledge_published':'ana.knowledge_unpublished',detail:publish?'Fonte aprovada para consulta da Ana.':'Fonte removida da consulta da Ana.',entity_table:'documents',entity_id:documentId,event_data:{name:existing.name,semantic}});return json({ok:true,status:nextStatus,semantic},200,headers)}
if(existing.storage_path?.startsWith(`${organizationId}/ana/`)){const{error}=await admin.storage.from('ana-knowledge').remove([existing.storage_path]);if(error&&!/not found/i.test(error.message))throw error}const{error:del}=await admin.from('documents').delete().eq('id',documentId).eq('organization_id',organizationId);if(del)throw del;await admin.from('audit_logs').insert({organization_id:organizationId,actor_id:user.id,actor_name:actorName,actor_type:'user',action:'ana.knowledge_deleted',detail:'Fonte removida da Base aprovada da Ana.',entity_table:'documents',entity_id:documentId,event_data:{name:existing.name}});return json({ok:true},200,headers)}catch(error){return json({ok:false,erro:safeError(error)},400,headers)}});
