import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ConfigureModal } from './IntegracoesTab';
import { useFontesStore } from '@/hooks/useFontesStore';
import { useIntegracoesStore, type OperationalIntegration } from '@/hooks/useIntegracoesStore';
import { loadOperationalDiagnostics, type OperationalDiagnostics } from '@/lib/crm/operationalDiagnosticsRepository';
import { supabase } from '@/lib/supabase';
import { detalheDoErroDeFuncao } from '@/lib/transportador';

type ApiView = 'overview' | 'ai' | 'prospecting' | 'history';
type HealthTone = 'positive' | 'attention' | 'critical' | 'neutral';

const names: Record<string, string> = { ai: 'OpenAI e Claude', apify: 'Apify — Google Maps', google_places: 'Google Places' };
const descriptions: Record<string, string> = {
  ai: 'Responde e prepara atendimentos.',
  apify: 'Extrai leads do Google Maps.',
  google_places: 'Fonte de dados de locais e empresas.',
};
const scopes: Record<string, string> = { ai: 'Ana', apify: 'Busca de Leads', google_places: 'Busca de Leads' };
const icons: Record<string, string> = { ai: 'ri-brain-line', apify: 'ri-map-pin-search-line', google_places: 'ri-google-line' };

function date(value: string | null | undefined): string {
  if (!value) return 'Ainda não testada';
  const parsed = new Date(value);
  return Number.isFinite(parsed.getTime()) ? parsed.toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : 'Data indisponível';
}

function healthFor(integration: OperationalIntegration): { label: string; tone: HealthTone; detail: string } {
  if (integration.status === 'validated') return { label: 'Pronto', tone: 'positive', detail: 'Validação recente confirmada pelo backend.' };
  if (integration.status === 'validation_due') return { label: 'Validação vencida', tone: 'attention', detail: 'A configuração está salva, mas precisa de nova validação.' };
  if (integration.status === 'error') return { label: 'Erro', tone: 'critical', detail: integration.lastError || 'A última validação falhou.' };
  if (integration.status === 'inactive') return { label: 'Desativado', tone: 'neutral', detail: 'O uso operacional está desativado; a configuração foi preservada.' };
  if (integration.status === 'paused') return { label: 'Pausado', tone: 'attention', detail: 'O backend mantém este provedor pausado.' };
  return { label: 'Credencial incompleta', tone: 'neutral', detail: 'Configure e valide para ativar.' };
}

function HealthBadge({ tone, children }: { tone: HealthTone; children: string }) {
  const styles: Record<HealthTone, string> = { positive: 'bg-[#E8F7EF] text-[#147445]', attention: 'bg-[#FFF1D8] text-[#9A5D11]', critical: 'bg-[#FFF0EE] text-[#A7352C]', neutral: 'bg-[#EEF1F3] text-[#68757D]' };
  const iconsByTone: Record<HealthTone, string> = { positive: 'ri-checkbox-circle-fill', attention: 'ri-error-warning-fill', critical: 'ri-close-circle-fill', neutral: 'ri-subtract-line' };
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${styles[tone]}`}><i className={iconsByTone[tone]} aria-hidden="true" />{children}</span>;
}

function UsageSwitch({ enabled, disabled, loading, label, onClick }: { enabled: boolean; disabled?: boolean; loading?: boolean; label: string; onClick?: () => void }) {
  return <button type="button" role="switch" aria-checked={enabled} aria-label={label} disabled={disabled || loading} onClick={onClick} className={`inline-flex items-center gap-2 disabled:cursor-not-allowed disabled:opacity-60`}><span className={`relative inline-flex h-6 w-10 items-center rounded-full p-1 transition ${enabled ? 'bg-[#168654]' : 'bg-[#CBD3D8]'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition ${enabled ? 'translate-x-4' : 'translate-x-0'}`} /></span><span className="text-xs font-semibold text-foreground-700">{loading ? 'Salvando…' : enabled ? 'Ativo' : 'Desativado'}</span></button>;
}

function ProviderCard({ integration, sourceStatus, pending, onConfigure, onTest, onToggle, onDiagnostic }: { integration: OperationalIntegration; sourceStatus?: string; pending: string | null; onConfigure: () => void; onTest: () => void; onToggle: () => void; onDiagnostic: () => void }) {
  const health = healthFor(integration);
  const isConfigured = integration.connected || integration.enabled;
  const canToggleOn = integration.connected && !integration.paused && !integration.lastError;
  const isLoading = pending === integration.remoteKey;
  // The public integration payload does not expose a configured fallback.
  // Never infer one from the selected primary provider.
  const fallback: string | null = null;
  return <article className="rounded-2xl border border-background-200 bg-white p-5 shadow-[0_5px_18px_rgba(20,31,38,0.03)]">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-background-100 text-xl text-foreground-800"><i className={icons[integration.remoteKey]} aria-hidden="true" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-base font-semibold text-foreground-950">{names[integration.remoteKey]}</h3><span className="rounded-full bg-[#EEF3FF] px-2.5 py-1 text-[11px] font-semibold text-[#4564A4]">{scopes[integration.remoteKey]}</span></div><p className="mt-1 text-sm text-foreground-500">{descriptions[integration.remoteKey]}</p></div><div className="flex shrink-0 items-center gap-3"><span className="text-xs font-semibold text-foreground-500">Uso operacional</span><UsageSwitch enabled={integration.enabled && !integration.paused} disabled={!canToggleOn && !integration.enabled} loading={isLoading} label={`Uso operacional de ${names[integration.remoteKey]}`} onClick={onToggle} /></div></div>
    <div className="mt-5 flex flex-col gap-3 border-t border-background-200/70 pt-4 lg:flex-row lg:items-center"><div className="flex flex-1 flex-wrap items-center gap-x-5 gap-y-2 text-xs text-foreground-500"><span><i className="ri-links-line mr-1.5" />Conexão: <strong className="font-semibold text-foreground-800">{integration.connected ? 'validada' : 'atenção'}</strong></span><span><i className="ri-calendar-line mr-1.5" />Último teste: <strong className="font-semibold text-foreground-800">{date(integration.lastTestedAt)}</strong></span>{fallback && <span><i className="ri-database-2-line mr-1.5" />Fallback: <strong className="font-semibold text-foreground-800">{fallback}</strong></span>}{sourceStatus && <span><i className="ri-search-line mr-1.5" />Fonte de busca: <strong className="font-semibold text-foreground-800">{sourceStatus}</strong></span>}</div><HealthBadge tone={health.tone}>{health.label}</HealthBadge></div>
    {!integration.connected && <p className="mt-3 rounded-lg bg-background-50 px-3 py-2 text-xs text-foreground-500">{health.detail}</p>}
    {integration.lastError && <p className="mt-3 rounded-lg bg-[#FFF4F2] px-3 py-2 text-xs text-[#8B3027]">{integration.lastError}</p>}
    <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={onConfigure} className="wf-btn-secondary text-xs"><i className="ri-settings-3-line" />Configurar</button><button type="button" disabled={isLoading || (!isConfigured && integration.remoteKey !== 'ai')} onClick={onTest} className="wf-btn-primary text-xs disabled:cursor-not-allowed disabled:opacity-50"><i className={isLoading ? 'ri-loader-4-line animate-spin' : 'ri-play-line'} />{isLoading ? 'Validando…' : 'Testar conexão'}</button><button type="button" onClick={onDiagnostic} className="wf-btn-secondary text-xs"><i className="ri-bar-chart-line" />{integration.remoteKey === 'google_places' && !isConfigured ? 'Ver motivo' : 'Diagnóstico'}</button></div>
  </article>;
}

export default function ApisProvidersTab() {
  const { integracoes, recarregar } = useIntegracoesStore();
  const { fontes, recarregar: recarregarFontes } = useFontesStore();
  const [view, setView] = useState<ApiView>('overview');
  const [diagnostics, setDiagnostics] = useState<OperationalDiagnostics | null>(null);
  const [configuring, setConfiguring] = useState<OperationalIntegration | null>(null);
  const [diagnosticKey, setDiagnosticKey] = useState<string | null>(null);
  const [pending, setPending] = useState<string | null>(null);
  const [notice, setNotice] = useState<{ tone: 'success' | 'error'; text: string } | null>(null);

  const refresh = useCallback(async () => { await Promise.all([recarregar(), recarregarFontes()]); try { setDiagnostics(await loadOperationalDiagnostics()); } catch { /* cards continuam exibindo o estado público já carregado */ } }, [recarregar, recarregarFontes]);
  useEffect(() => { void refresh(); }, [refresh]);

  const providers = useMemo(() => ['ai', 'apify', 'google_places'].map((key) => integracoes.find((item) => item.remoteKey === key)).filter(Boolean) as OperationalIntegration[], [integracoes]);
  const ai = providers.find((item) => item.remoteKey === 'ai');
  const prospecting = providers.filter((item) => item.remoteKey !== 'ai');
  const sourceByKey = new Map(fontes.map((source) => [source.sourceKey, source]));
  const actionRequired = providers.filter((item) => item.status === 'validation_due' || item.status === 'error' || item.status === 'not_configured').length;
  const selectedDiagnostic = providers.find((item) => item.remoteKey === diagnosticKey) || null;

  const messageFor = (error: unknown) => { const code = error instanceof Error ? error.message : ''; if (code === 'integration_validation_required') return 'Valide a conexão novamente antes de ativar o uso operacional.'; if (code === 'permission_denied') return 'Seu usuário não possui permissão para alterar este provedor.'; return 'Não foi possível concluir a ação. O estado visual foi revertido pelo backend.'; };
  const test = async (integration: OperationalIntegration) => { setPending(integration.remoteKey); setNotice(null); try { const { data, error } = await supabase.functions.invoke('testar-integracao', { body: { canal: integration.remoteKey } }); if (error || !data?.pronto) throw new Error(error ? await detalheDoErroDeFuncao(error) : data?.erro || data?.detalhe); await refresh(); setNotice({ tone: 'success', text: `${names[integration.remoteKey]} validado contra o serviço real. Nenhuma mensagem foi enviada.` }); } catch (error) { await refresh(); setNotice({ tone: 'error', text: messageFor(error) }); } finally { setPending(null); } };
  const toggle = async (integration: OperationalIntegration) => { const enabling = !integration.enabled || integration.paused; if (!enabling && !window.confirm(`Desativar ${names[integration.remoteKey]} interrompe seu uso operacional, mas preserva a configuração. Continuar?`)) return; if (enabling && (!integration.connected || integration.paused || integration.lastError)) { setNotice({ tone: 'error', text: 'A ativação está bloqueada até a credencial e a validação serem confirmadas.' }); return; } setPending(integration.remoteKey); setNotice(null); try { const { data, error } = await supabase.functions.invoke('configurar-integracao', { body: { action: 'set_usage', canal: integration.remoteKey, enabled: enabling } }); if (error || !data?.ok) throw new Error(error ? await detalheDoErroDeFuncao(error) : data?.erro || 'integration_usage_save_failed'); await refresh(); setNotice({ tone: 'success', text: enabling ? `${names[integration.remoteKey]} ativado para uso operacional.` : `${names[integration.remoteKey]} desativado; configuração preservada.` }); } catch (error) { await refresh(); setNotice({ tone: 'error', text: messageFor(error) }); } finally { setPending(null); } };
  const validateAll = async () => { for (const provider of providers) await test(provider); };

  return <div className="space-y-5" data-testid="apis-providers-tab">
    <header className="flex flex-col gap-3 border-b border-background-200/70 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="wf-eyebrow">Configurações</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-foreground-950">APIs e provedores</h2><p className="mt-1 text-sm text-foreground-500">Credenciais, validação e uso operacional.</p></div><div className="flex flex-wrap gap-2"><Link to="/dashboard/configuracoes?tab=registro" className="wf-btn-secondary text-xs"><i className="ri-history-line" />Registro de auditoria</Link><button type="button" className="wf-btn-primary text-xs" disabled={Boolean(pending)} onClick={() => void validateAll()}><i className="ri-play-line" />Validar tudo</button></div></header>
    {actionRequired > 0 && <div className="flex flex-col gap-3 rounded-xl border border-[#F0C171] bg-[#FFF8E9] px-4 py-3 text-[#8B5A1D] sm:flex-row sm:items-center"><i className="ri-error-warning-fill text-xl" aria-hidden="true" /><div className="flex-1"><p className="text-sm font-semibold text-[#744514]">{actionRequired} integrações exigem ação</p><p className="mt-0.5 text-xs">Revise credenciais e execute uma nova validação antes de ativar o uso operacional.</p></div><button type="button" className="wf-btn-secondary text-xs" onClick={() => setView('overview')}>Revisar agora <i className="ri-arrow-right-line" /></button></div>}
    {notice && <div role="status" className={`rounded-xl border px-3.5 py-3 text-sm ${notice.tone === 'success' ? 'border-[#B9E4CB] bg-[#EFFAF3] text-[#176B43]' : 'border-[#E8B8B1] bg-[#FFF4F2] text-[#8B3027]'}`}>{notice.text}</div>}
    <nav className="flex flex-wrap items-center justify-between gap-3 border-b border-background-200" aria-label="Seções de APIs"><div className="flex gap-5"><button type="button" className={`border-b-2 px-1 pb-3 text-sm font-semibold ${view === 'overview' ? 'border-primary-600 text-primary-700' : 'border-transparent text-foreground-500'}`} onClick={() => setView('overview')}>Visão geral</button><button type="button" className={`border-b-2 px-1 pb-3 text-sm font-semibold ${view === 'ai' ? 'border-primary-600 text-primary-700' : 'border-transparent text-foreground-500'}`} onClick={() => setView('ai')}>IA da Ana</button><button type="button" className={`border-b-2 px-1 pb-3 text-sm font-semibold ${view === 'prospecting' ? 'border-primary-600 text-primary-700' : 'border-transparent text-foreground-500'}`} onClick={() => setView('prospecting')}>Busca de Leads</button><button type="button" className={`border-b-2 px-1 pb-3 text-sm font-semibold ${view === 'history' ? 'border-primary-600 text-primary-700' : 'border-transparent text-foreground-500'}`} onClick={() => setView('history')}>Histórico</button></div><div className="hidden items-center gap-4 text-[11px] text-foreground-500 md:flex"><span><i className="ri-toggle-line mr-1 text-[#168654]" />Uso operacional</span><span><i className="ri-checkbox-circle-fill mr-1 text-[#168654]" />Saúde técnica: ok</span><span><i className="ri-error-warning-fill mr-1 text-[#D68411]" />Atenção</span><span><i className="ri-close-circle-fill mr-1 text-[#BD3D32]" />Problema</span></div></nav>
    {(view === 'overview' || view === 'ai') && ai && <section><h3 className="mb-3 text-lg font-semibold text-foreground-950">IA da Ana</h3><ProviderCard integration={ai} pending={pending} onConfigure={() => setConfiguring(ai)} onTest={() => void test(ai)} onToggle={() => void toggle(ai)} onDiagnostic={() => setDiagnosticKey(ai.remoteKey)} /></section>}
    {(view === 'overview' || view === 'prospecting') && <section><h3 className="mb-3 text-lg font-semibold text-foreground-950">Busca de Leads</h3><div className="grid gap-4 xl:grid-cols-2">{prospecting.map((integration) => <ProviderCard key={integration.remoteKey} integration={integration} sourceStatus={sourceByKey.get(integration.remoteKey)?.status === 'ativo' ? 'ativa' : sourceByKey.get(integration.remoteKey)?.status === 'inativo' ? 'desativada' : 'aguardando validação'} pending={pending} onConfigure={() => setConfiguring(integration)} onTest={() => void test(integration)} onToggle={() => void toggle(integration)} onDiagnostic={() => setDiagnosticKey(integration.remoteKey)} />)}</div></section>}
    {(view === 'overview' || view === 'history') && <section className="wf-surface overflow-hidden"><div className="flex items-center justify-between border-b border-background-200/70 px-5 py-4"><div><h3 className="text-base font-semibold text-foreground-950">Atividade recente</h3><p className="mt-1 text-xs text-foreground-500">Últimas ações relacionadas às integrações e validações.</p></div><button type="button" className="text-xs font-semibold text-primary-700" onClick={() => setView('history')}>Ver histórico completo <i className="ri-arrow-right-line" /></button></div><div className="divide-y divide-background-200/70">{(diagnostics?.audit || []).filter((event) => (event.action || '').includes('integration')).slice(0, view === 'history' ? 20 : 3).map((event) => <div key={event.id} className="grid gap-2 px-5 py-3 sm:grid-cols-[minmax(12rem,1fr)_minmax(0,2fr)_auto] sm:items-center"><div><p className="text-sm font-semibold text-foreground-800">{event.action?.replaceAll('.', ' · ') || 'Evento de integração'}</p><p className="mt-1 text-[11px] text-foreground-400">{event.actor_name || 'Sistema'} · {date(event.occurredAt || event.created_at)}</p></div><p className="text-xs text-foreground-600">{event.detail || event.error_message || event.error || 'Sem detalhe adicional.'}</p><HealthBadge tone={event.status === 'failed' || event.error ? 'critical' : 'positive'}>{event.status === 'failed' || event.error ? 'Atenção' : 'Registrado'}</HealthBadge></div>)}{(!diagnostics?.audit || diagnostics.audit.filter((event) => (event.action || '').includes('integration')).length === 0) && <p className="px-5 py-8 text-center text-sm text-foreground-500">Nenhuma atividade de integração retornada pelo backend.</p>}</div></section>}
    {configuring && <ConfigureModal integration={configuring} onClose={() => setConfiguring(null)} onSaved={async () => { await refresh(); setConfiguring(null); }} />}
    {selectedDiagnostic && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#14151A]/45 p-4" role="presentation" onClick={() => setDiagnosticKey(null)}><section className="w-full max-w-lg rounded-2xl border border-background-200 bg-white shadow-xl" role="dialog" aria-modal="true" aria-labelledby="api-diagnostic-title" onClick={(event) => event.stopPropagation()}><header className="flex items-start justify-between border-b border-background-200 px-5 py-4"><div><p className="wf-eyebrow">Diagnóstico</p><h3 id="api-diagnostic-title" className="mt-1 text-lg font-semibold text-foreground-950">{names[selectedDiagnostic.remoteKey]}</h3></div><button type="button" className="rounded-lg p-2 text-foreground-500 hover:bg-background-100" onClick={() => setDiagnosticKey(null)} aria-label="Fechar diagnóstico"><i className="ri-close-line text-lg" /></button></header><div className="space-y-3 p-5"><div className="flex items-center justify-between rounded-xl bg-background-50 px-3.5 py-3"><span className="text-sm text-foreground-600">Estado da credencial</span><HealthBadge tone={healthFor(selectedDiagnostic).tone}>{selectedDiagnostic.connected ? 'Confirmada' : 'Pendente'}</HealthBadge></div><div className="flex items-center justify-between rounded-xl bg-background-50 px-3.5 py-3"><span className="text-sm text-foreground-600">Último teste</span><strong className="text-sm text-foreground-900">{date(selectedDiagnostic.lastTestedAt)}</strong></div><div className="rounded-xl bg-background-50 px-3.5 py-3"><p className="text-xs text-foreground-500">Motivo</p><p className="mt-1 text-sm leading-5 text-foreground-800">{healthFor(selectedDiagnostic).detail}</p></div><div className="rounded-xl bg-background-50 px-3.5 py-3"><p className="text-xs text-foreground-500">Próxima ação</p><p className="mt-1 text-sm leading-5 text-foreground-800">{selectedDiagnostic.connected ? 'Execute uma nova validação quando o prazo vencer.' : 'Configure e valide a credencial no cofre seguro.'}</p></div><p className="text-xs text-foreground-500">Identificador de correlação: não retornado pelo backend para esta integração.</p></div><footer className="flex justify-end gap-2 border-t border-background-200 px-5 py-4"><button type="button" className="wf-btn-secondary text-xs" onClick={() => setDiagnosticKey(null)}>Fechar</button><button type="button" className="wf-btn-primary text-xs" onClick={() => { setDiagnosticKey(null); void test(selectedDiagnostic); }}>Testar conexão</button></footer></section></div>}
  </div>;
}
